### ISSUE TITLE
Pagination problem 

### ISSUE THREAD

**Issue by lablushah** [vedcasts/series-vuejs-project#2]
On html file line number 214:
<li
                            v-repeat="pagination.pageNumbers"
                            v-class="active:$value == pagination.currentPage">
                            <a href="#" v-on="click:page($event, $value)">{{ $value }}</a>
                        </li>

v-repeat does not have alias which it stops rendering the pagination properly. Don't know what it should be.

Any help!

**Comment by vedovelli** [comment]
Because you're using the version 1.0 of Vue.js you're forced to use an alias. 

So the code should be as follows:

``` html
<div
   v-for="pageNumber as pagination.pageNumbers"
   v-bind:class="{ 'active': pageNumber == pagination.currentPage }"
```

In every place you see **$value** now you use **pageNumber** which is the alias.

Try that and let me know if it works!

Ved

**Comment by lablushah** [comment]
Thanks for quick reply; trying it now.
