### ISSUE TITLE
SEARCH COMPETENCY

### ISSUE THREAD

**Issue by lablushah** [vedcasts/series-vuejs-project#3]
What happens in case of huge amount of records, for example, 100,000 records. It seems that it will receive all data in one shot. Any idea!

Note: On vue 1.0 

"if(self.interaction.filterTerm != '' && self.interaction.columnsToFilter.length > 0)" gives this error: 

Uncaught TypeError: Cannot read property 'length' of null,

When Reseting All and trying to search without selecting columnsToFilter,  

Trying to fix it , but failed. 

I guess same thing will happen when it goes "return self.interaction.columnsToFilter.some(function(column)" line.

Any suggestion!

Thanks,

Monjurul

**Comment by vedovelli** [comment]
This kind of questioning fits better in the series comment system. Please add there and we shall discuss it! Thanks!
